export interface IFilmDetail {
    actorList?: [],
    awards?: string,
    boxOffice?: {},
    companies?: string,
    companyList?: [],
    contentRating?: string,
    countries?: string,
    countryList?: [],
    directorList: any[],
    directors?: string,
    errorMessage?: string,
    fullCast?: [] | string,
    fullTitle?: string,
    genreList?: [],
    genres?: string,
    id?: string,
    imDbRating?: string,
    imDbRatingVotes?: string,
    image?: string,
    images?: [] | string, 
    keywordList?: [],
    keywords?: string,
    languageList?: [],
    languages?: string,
    metacriticRating?: string,
    originalTitle?: string,
    plot?: string,
    plotLocal?: string,
    plotLocalIsRtl?: boolean,
    posters?: string | [],
    ratings?: string | [],
    releaseDate?: string,
    runtimeMins?: string,
    runtimeStr?: string,
    similars?: IFilmDetail[],
    starList: any[],
    stars?: string,
    tagline?: string | [],
    title?: string,
    trailer?: string | [],
    tvEpisodeInfo?: string | [],
    tvSeriesInfo?: string | [],
    type?: string,
    wikipedia?: string | [],
    writerList?: [],
    writers?: string,
    year?: string,
}